- name: Install Nginx
  apt:
    name: nginx
    state: latest
- name: Replace NGINX config
  template: 
    src=templates/nginx.conf
    dest=/etc/nginx/nginx.conf

- name: Add NGINX cloud config
  template:
    src=templates/cloud.conf
    dest=/etc/nginx/conf.d/{{ upstream_url_cloud }}.conf
    
- name: Add NGINX host config
  template:
    src=templates/host.conf
    dest=/etc/nginx/conf.d/{{ upstream_url_host }}.conf
    
- name: Add NGINX torrent config
  template:
    src=templates/torrent.conf
    dest=/etc/nginx/conf.d/{{ upstream_url_torrent }}.conf
    
- name: Add NGINX plex config
  template:
    src=templates/plex.conf
    dest=/etc/nginx/conf.d/{{ upstream_url_plex }}.conf

- name: Add NGINX mysql config
  template:
    src=templates/mysql.conf
    dest=/etc/nginx/conf.d/{{ upstream_url_mysql }}.conf

- name: Add NGINX ldap config
  template:
    src=templates/ldap.conf
    dest=/etc/nginx/conf.d/{{ upstream_url_ldap }}.conf 
 
- name: Add NGINX mail config
  template:
    src=templates/mail.conf
    dest=/etc/nginx/conf.d/{{ upstream_url_mail }}.conf 

- name: Add NGINX postfix config
  template:
    src=templates/postfix.conf
    dest=/etc/nginx/conf.d/{{ upstream_url_postfix }}.conf 

- name: Add NGINX web config
  template:
    src=templates/web.conf
    dest=/etc/nginx/conf.d/{{ upstream_url_web }}.conf
    
- name: Set timezone to Asia/Irkutsk
  timezone:
    name: Asia/Irkutsk
  
- name: Nginx reload 
  notify:
    - NGINX reload
