- name: Install Nginx
  apt:
    name: nginx
    state: latest
- name: Replace NGINX config
  template: 
    src=templates/nginx.conf
    dest=/etc/nginx/nginx.conf

- name: Add NGINX cloud config
  template:
    src=templates/cloud.conf
    dest=/etc/nginx/conf.d/{{ upstream_url_cloud }}.conf
    
- name: Add NGINX host config
  template:
    src=templates/host.conf
    dest=/etc/nginx/conf.d/{{ upstream_url_host }}.conf
    
- name: Add NGINX torrent config
  template:
    src=templates/torrent.conf
    dest=/etc/nginx/conf.d/{{ upstream_url_torrent }}.conf
    
  notify:
    - NGINX reload