- name: Install Nginx
  apt:
    name: nginx
    state: latest
- name: Replace NGINX config
  template: 
    src=templates/nginx.conf
    dest=/etc/nginx/nginx.conf

- name: Add NGINX virtualhost config
  template:
    src=templates/cloud.conf
    dest=/etc/nginx/conf.d/{{ upstream_url_cloud }}.conf
  notify:
    - NGINX reload