- hosts: routers
  user: root
  gather_facts: false
  connection: network_cli

  vars:
  - ansible_ssh_user: root
  tasks:
    - name: system command
      routeros_command:
        commands: /system routerboard print

